Câu 1: Viết chương trình tạo hai Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số
nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 4). Sau đó chuyển vị array, tensor thứ 2
và thực hiện phép nhân matrix multiplication. Lưu ý: sử dụng seed=2024

In [1]:
import numpy as np
import torch
import tensorflow as tf
import random

In [36]:
shape = (3, 4)

np.random.seed(2024)
arr1 = np.random.randint(-10, 10, shape)
print('Matrix 1')
print(arr1)

torch.manual_seed(seed=2024)
arr2 = torch.randint(-10, 10, size=shape)

# Transpose second matrix
arr2 = arr2.transpose(0, 1)
print('Matrix 2')
print(arr2)

# Matrix multiplication
print('Matrix multiplication')
print('\t Matrix 2 x 1: (4,4)')
print(np.dot(arr2,arr1))
print('\t Matrix 1 x 2: (3,3)')
print(np.dot(arr1,arr2))

Matrix 1
[[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
Matrix 2
tensor([[  2,  -7,   3],
        [  0, -10,   9],
        [ -6,   0,   7],
        [-10,   1,  -6]])
Matrix multiplication
	 Matrix 2 x 1: (4,4)
[[-21  13  14   9]
 [-62   0  25  63]
 [-44 -10  25  85]
 [ 67 151 123  18]]
	 Matrix 1 x 2: (3,3)
[[ 116  108 -130]
 [  40   97 -133]
 [ -56  163 -191]]


Câu 2: Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số
nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 3). Sau đó hãy tính tổng của toàn bộ
tensor, array, tiếp theo tính tổng theo chiều dọc, chiều ngang . Lưu ý: sử dụng seed=2024

In [46]:
def sum_arr(data):
    print(data)
    print(f'Sum all = {data.sum()}')
    print(f"Sum of each column : \n {data.sum(axis = 0,keepdims = True )}")
    print(f"Sum of each row : \n {data.sum(axis = 1,keepdims = True )}")


In [50]:
shape2 = (3,3)

print('Numpy Random Array')
np.random.seed(2024)
data1 = np.random.randint(-10,10,shape2)
sum_arr(data1)

print('Pytorch Random Tensor')
torch.manual_seed(2024)
data2 = torch.randint(-10,10,shape2)
sum_arr(data2)

Numpy Random Array
[[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
Sum all = -53
Sum of each column : 
 [[-15 -11 -27]]
Sum of each row : 
 [[-22]
 [-16]
 [-15]]
Pytorch Random Tensor
tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
Sum all = -27
Sum of each column : 
 tensor([[ -8,  -6, -13]])
Sum of each row : 
 tensor([[ -4],
        [-27],
        [  4]])
