In [5]:
import numpy as np

# pip3 install torch torchvision torchaudio
import torch

#pip install tensorflow
import tensorflow as tf


In [10]:
lst_1D = [1,3,2,4,7,4,6,4]
print(np.array(lst_1D))

print(torch.Tensor(lst_1D))

print(tf.constant(lst_1D))

[1 3 2 4 7 4 6 4]
tensor([1., 3., 2., 4., 7., 4., 6., 4.])
tf.Tensor([1 3 2 4 7 4 6 4], shape=(8,), dtype=int32)


In [21]:
lst_2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


def check(data):
    for _ in (data.shape, data.dtype, type(data), data):
        print(_)

np_ar2 = np.array(lst_2D)
tensor_torch = torch.tensor(lst_2D)
tf_tensor = tf.constant(lst_2D)


print("Numpy Array:")
check(np_ar2)
print('Pytorch Tensor')
check(tensor_torch)
print(tensor_torch.device)
print('TF Tensor')
check(tf_tensor)
print(tf_tensor.device)

Numpy Array:
(3, 3)
int32
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Pytorch Tensor
torch.Size([3, 3])
torch.int64
<class 'torch.Tensor'>
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
cpu
TF Tensor
(3, 3)
<dtype: 'int32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
/job:localhost/replica:0/task:0/device:CPU:0
