In [1]:
import numpy as np
import torch
import tensorflow as tf

Hàm zeros và ones

In [7]:
print (np.zeros((2,3)))
print (torch.zeros((3,4)))
print (tf.ones((1,2,3)))


[[0. 0. 0.]
 [0. 0. 0.]]
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


Hàm full (Pytorch and Numpy) và fill (TF)

In [8]:
np.full((1,3),4)

array([[4, 4, 4]])

In [9]:
torch.full((2,5),17)

tensor([[17, 17, 17, 17, 17],
        [17, 17, 17, 17, 17]])

In [10]:
tf.fill((2,3),1324.1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1324.1, 1324.1, 1324.1],
       [1324.1, 1324.1, 1324.1]], dtype=float32)>